In [15]:
import pandas as pd
import numpy as np

In [16]:
data_19 = pd.read_excel('../data/raw_data/2019 Power sector Energy Generated.xlsx', sheet_name = 'Energy Consumed (MWH) 2019', header = 1, index_col = 0)
data_19 = data_19.drop([np.nan, 'JAN-JUNE TOTAL', 'JUL-DEC TOTAL'])

In [17]:
data_19

,ABUJA,IBADAN,EKO,IKEJA,BENIN,JOS,KADUNA,YOLA,PORTHARCOURT,ENUGU,KANO,TOTAL
REGION,,,,,,,,,,,,
JANUARY,320061.47,300517.35,296600.74,312172.06,223259.42,111088.85,195788.57,94458.7,264543.06,155439.79,149800.32,2423730.33
FEBRUARY,299146.05,282012.62,289100.56,309221.44,216306.22,96925.70,181804.62,93449.5,253260.18,141727.94,158790.61,2321745.44
MARCH,357128.35,285941.91,327956.86,360745.64,228707.71,104736.55,192970.61,118062.3,267083.55,149431.14,158790.61,2551555.23
APRIL,341874.02,283503.08,274755.11,322408.60,229247.05,91786.20,158627.95,103794.3,266421.16,144944.91,175720.04,2393082.42
MAY,300917.63,293824.75,291532.68,337215.92,188596.97,97371.45,172991.07,86969.4,269149.32,134263.97,162974.20,2335807.36
JUNE,318251.01,268959.20,263948.15,328926.25,165231.22,105167.00,164246.76,87232.6,261300.63,125767.58,158678.33,2247708.73
JULY,298248.45,296929.18,289065.84,338912.36,188120.80,101331.60,163813.08,81802.3,245091.18,130954.58,146512.43,2280781.80
AUGUST,322835.63,305772.70,310502.47,350778.87,182425.49,93479.00,146742.54,90162.0,231147.85,140498.50,130347.94,2304692.99
SEPTEMBER,267685.55,268909.60,275655.05,337057.65,182952.06,100067.95,124131.60,83674.0,240644.14,127219.86,128121.04,2136118.50
OCTOBER,278072.54,287914.26,269595.35,334432.30,177257.33,106916.75,134280.10,93764.0,261006.52,130172.09,146421.10,2219832.34
NOVEMBER,305207.00,312465.05,306970.12,364651.69,189377.27,104976.90,143565.56,100388.2,268760.93,131471.31,141872.63,2369706.66
DECEMBER,290075.52,336656.92,315507.01,391448.40,199816.32,110850.05,132085.54,88777.2,293998.87,138865.77,143659.62,2441741.22
ANNUAL TOTAL,3699503.22,3523406.62,3511189.94,4087971.18,2371297.86,1224698.00,1911048.00,1122534.5,3122407.39,1650757.44,1801688.87,28026503.02

In [18]:
with pd.ExcelWriter('../data/processed_data/Energy_consumption.xlsx') as writer:
    data_19.to_excel(writer, sheet_name = 'Consumption in 2019')

In [19]:
data_20 = pd.read_excel('../data/raw_data/Energy report 2020.xlsx', sheet_name = 'Monthly',skiprows = 37, index_col = 0)

In [20]:
data_20.columns = ['Source', 'Jan-20', 'Feb-20', 'Mar-20', 'Q1 2020', 'Apr-20', 'May-20', 'Jun-20', 'Q2 2020', 'Jul-20', 'Aug-20', 'Sep-20', 'Q3 2020', 'Oct-20', 'Nov-20', 'Dec-20', 'Q4 2020']

In [21]:
data_20

,Source,Jan-20,Feb-20,Mar-20,Q1 2020,Apr-20,May-20,Jun-20,Q2 2020,Jul-20,Aug-20,Sep-20,Q3 2020,Oct-20,Nov-20,Dec-20,Q4 2020
AFAM (I-V),Thermal,54.000000,57.000000,53.000000,164.000000,28.000000,32.000000,28.000000,88.000000,21.000000,31.000000,11.000000,63.000000,39.000000,44.000000,46.000000,129.000000
GEREGU,Thermal,200.588000,158.909000,98.808000,458.305000,171.234000,217.081000,137.830000,526.145000,134.229000,153.307000,156.501000,444.037000,155.919000,203.624000,235.128000,594.671000
EGBIN,Thermal,377.119100,400.626100,425.107700,1202.852900,393.316000,367.494700,347.680000,1108.490700,321.251200,342.833100,308.306900,972.391200,383.030800,414.506600,459.979600,1257.517000
SAPELE,Thermal,19.857120,17.424090,15.698340,52.979550,26.933070,32.148080,19.337400,78.418550,23.836550,34.797740,19.643710,78.278000,25.937120,33.437040,38.952700,98.326860
UGHELLI,Thermal,187.322500,162.807800,200.673200,550.803500,248.990900,265.804980,247.591100,762.386980,249.516400,227.301100,217.829700,694.647200,227.843700,238.046500,212.851300,678.741500
SHIRORO,Hydro,203.200000,209.450000,260.740000,673.390000,172.320000,125.120000,98.400000,395.840000,181.700000,278.000000,292.000000,751.700000,281.000000,272.000000,248.000000,801.000000
KAINJI,Hydro,299.672000,289.799700,294.255000,883.726700,245.074000,206.244800,185.122000,636.440800,187.056000,229.783900,190.688800,607.528700,254.917000,269.729000,267.154000,791.800000
JEBBA,Hydro,274.839100,215.117200,220.672500,710.628800,197.147300,201.232800,164.040600,562.420700,207.062900,241.889800,207.550000,656.502700,234.740900,256.153710,261.266500,752.161110
AES BARGE,Thermal,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
OKPAI,Thermal,94.497100,68.372100,96.881400,259.750600,115.753500,117.229900,113.762200,346.745600,156.738200,222.464300,229.854500,609.057000,157.656700,109.583800,108.447500,375.688000
AFAM VI,Thermal,120.690856,131.787051,221.000000,473.477907,198.280805,210.585219,196.356999,605.223023,170.032760,194.236246,155.798050,520.067056,200.001691,184.984501,246.501898,631.488090
OMOKU,Thermal,51.079700,48.950500,47.308800,147.339000,52.337000,47.615000,45.145000,145.097000,44.293000,45.175600,17.733700,107.202300,23.902400,33.983000,24.889600,82.775000
TRANS-AMADI,Thermal,0.000000,35.766900,51.644000,87.410900,49.303700,50.610300,50.613700,150.527700,38.365000,26.946900,30.002200,95.314100,53.964300,44.276200,54.538900,152.779400
RIVERS IPP,Thermal,65.805600,93.104000,80.039800,238.949400,72.134800,83.878500,83.393500,239.406800,74.405000,93.708000,73.710000,241.823000,69.599000,70.486000,52.156900,192.241900
IBOM POWER,Thermal,11.627000,8.400000,0.000000,20.027000,26.109000,43.164000,46.703000,115.976000,47.546000,26.380000,22.318000,96.244000,12.771000,35.421000,42.164000,90.356000
OLORUNSOGO,Thermal,80.049000,60.551900,58.811400,199.412300,83.608900,90.444500,88.442600,262.496000,123.470100,122.943000,109.159100,355.572200,110.977500,101.468200,90.171900,302.617600
OMOTOSHO,Thermal,63.139000,67.480600,68.580500,199.200100,70.740900,96.104000,82.062400,248.907300,106.518100,110.237800,106.065000,322.820900,108.520900,99.852600,76.711800,285.085300
OLORUNSOGO NIPP,Thermal,0.785000,21.600000,0.000000,22.385000,25.000000,37.800000,12.000000,74.800000,17.000000,0.000000,0.000000,17.000000,NaN,9.829000,0.673000,10.502000
OMOTOSHO NIPP,Thermal,53.877200,56.605800,25.684900,136.167900,68.049300,66.258400,46.547900,180.855600,47.971900,44.031130,48.423500,140.426530,52.006300,71.304200,71.243000,194.553500
ALAOJI NIPP,Thermal,4.673620,74.855190,125.848570,205.377380,83.435290,66.046940,29.165790,178.648020,32.737180,21.067000,6.817750,60.621930,43.882670,52.395730,0.000000,96.278400
SAPELE NIPP,Thermal,10.153000,0.000000,0.000000,10.153000,0.000000,0.000000,0.000000,0.000000,20.556800,20.989380,44.002300,85.548480,54.335600,44.270440,57.493050,156.099090
IHOVBOR NIPP,Thermal,13.364690,6.988980,0.000000,20.353670,14.861720,22.621690,4.678930,42.162340,34.112880,19.462860,39.094380,92.670120,28.716270,0.000000,0.000000,28.716270
GEREGU NIPP,Thermal,83.240000,77.101980,70.960000,231.301980,72.630000,66.670000,51.690000,190.990000,54.270000,56.140000,59.220000,169.630000,59.160000,80.640000,84.280000,224.080000
CALABAR NIPP,Thermal,224.803090,221.241450,240.837950,686.882490,203.957560,273.296840,249.979020,727.233420,191.471020,118.716470,69.585620,379.773110,163.821950,245.357540,255.700040,664.879530
NESCO,Hydro,6.890000,6.405000,6.670000,19.965000,6.300000,6.630000,5.960000,18.890000,6.640000,6.940000,5.730000,19.310000,6.030000,4.170000,2.560000,12.760000
PARAS,Thermal,47.998117,44.612669,46.558367,139.169154,46.868266,47.524758,46.282157,140.675181,48.618821,48.613726,46.867387,144.099934,48.598689,47.117301,48.230206,143.946196
GBARAIN,Thermal,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
AZURA-EDO,Thermal,227.164300,226.875700,142.253500,596.293500,235.483300,289.120700,269.255800,793.859800,274.696200,257.315200,273.374000,805.385400,277.369100,155.871300,306.687300,739.927700
DADIN KOWA,Hydro,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000

In [22]:
with pd.ExcelWriter('../data/processed_data/Energy_consumption.xlsx', engine = 'openpyxl', mode = "a") as writer:
    data_20.to_excel(writer, sheet_name = 'Consumption in 2020')

In [23]:
data_21 = pd.read_excel('../data/raw_data/DISCOS ELECTRICITY REPORT 2021.xlsx' ,skiprows = 2, nrows = 13, header = 0, index_col = 1)

In [24]:
data_21 = data_21.drop(['Unnamed: 0'], axis =1)

In [25]:
data_21.columns = ['JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY',
       'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', 'Total', '2020', 'a', 'b', 'c']

In [26]:
data_21 = data_21.drop([ 'a', 'b', 'c'], axis =1)

In [27]:
data_21

,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER,Total,2020
DISCOS,,,,,,,,,,,,,,
TOTAL,2097.568375,2101.253905,1973.366755,2042.986540,1955.343360,1884.241882,1747.027246,1865.439878,1880.168772,1840.408950,1972.629029,2000.154835,23360.589527,22042.280008
ABUJA (AEDC),218.000000,226.000000,229.000000,245.000000,231.000000,211.000000,206.000000,223.000000,211.000000,217.000000,225.000000,235.000000,2677.000000,2388.000000
BENIN (BEDC),200.504476,203.848963,179.630103,202.004241,180.986591,187.810117,172.391180,187.851700,178.301912,173.567699,190.741623,182.735847,2240.374451,2138.115855
EKO (EKEDC),300.000000,297.880287,271.590137,262.000000,252.861761,249.436155,229.547498,249.461451,262.766926,242.688884,271.965378,269.000000,3159.198477,3097.873500
ENUGU (EEDC),193.000000,201.000000,184.000000,179.000000,166.000000,163.000000,151.000000,168.000000,162.000000,157.000000,159.800000,163.000000,2046.800000,1700.000000
IBADAN (IBEDC),300.645202,305.318615,268.273762,270.246883,252.013780,207.557577,180.322862,218.963407,224.746495,232.821954,240.834471,255.427647,2957.172657,2841.084669
IKEJA (IEDC),359.398436,359.917321,351.405779,352.701161,341.928826,346.826724,322.040736,334.463747,323.203248,314.872730,339.553037,342.304585,4088.616329,4158.870044
JOS (JEDC),69.560678,69.514924,68.391723,67.497874,70.774540,87.784576,78.315083,77.196098,84.411301,86.866727,89.933625,92.902872,943.150022,789.458455
KADUNA (KDEDC),144.000000,138.000000,129.000000,150.000000,156.000000,147.000000,139.000000,142.000000,148.000000,147.000000,156.000000,161.000000,1757.000000,1398.000000
KANO (KEDC),123.187681,119.820479,121.516274,132.157170,124.994867,115.082066,108.697092,98.151292,115.933961,106.992423,127.940849,136.542122,1431.016276,1428.687681
PORT HARCOURT (PEDC),142.271902,135.953317,138.558976,146.379211,144.782996,135.744667,127.712796,132.352182,137.804929,129.598532,137.860045,129.241761,1638.261315,1545.189805
YOLA (YEDC),47.000000,44.000000,32.000000,36.000000,34.000000,33.000000,32.000000,34.000000,32.000000,32.000000,33.000000,33.000000,422.000000,557.000000
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
with pd.ExcelWriter('../data/processed_data/Energy_consumption.xlsx', engine = 'openpyxl', mode = "a") as writer:
    data_21.to_excel(writer, sheet_name = 'Consumption in 2021')

In [32]:
data_22_1 = pd.read_excel('../data/raw_data/ELECTRICIY DATA 2015-Q4 2022.xlsx' ,skiprows = 65, header = 0, index_col = 0)

In [33]:
data_22_1

,2015-01-01 00:00:00,2015-02-01 00:00:00,2015-03-01 00:00:00,2015-04-01 00:00:00,2015-05-01 00:00:00,2015-06-01 00:00:00,2015-07-01 00:00:00,2015-08-01 00:00:00,2015-09-01 00:00:00,2015-10-01 00:00:00,...,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00,TOTAL.7,Q3,Q4
DISCOS,1731.976127,1699.355150,1522.954093,1587.924630,1393.060383,1189.596685,1569.773986,1840.167840,1961.059817,1950.038770,...,1699.847514,1511.247280,1710.177145,1802.537580,1813.719086,1848.537254,1948.392986,21817.099808,5023.962005,5610.649326
ABUJA (AEDC),246.000000,250.000000,244.000000,236.000000,212.000000,156.000000,227.000000,220.000000,250.000000,268.000000,...,191.000000,195.000000,217.000000,234.000000,239.000000,255.000000,251.000000,2656.000000,646.000000,745.000000
BENIN (BEDC),165.020000,130.930000,125.470000,128.870000,134.700000,103.310000,102.840000,125.430000,128.150000,138.560000,...,176.338973,162.657932,183.637713,187.940295,197.140591,204.620000,193.322185,2278.478444,534.235939,595.082776
EKO (EKEDC),191.795167,195.000000,155.016759,163.000000,133.517640,117.252571,177.000000,223.446965,234.114897,245.892348,...,222.000000,183.000000,211.000000,245.000000,237.000000,240.000000,271.000000,2768.387434,639.000000,748.000000
ENUGU (EEDC),162.000000,159.000000,146.000000,139.000000,136.000000,118.000000,148.000000,158.000000,168.000000,155.000000,...,145.000000,144.000000,162.000000,144.000000,138.000000,138.000000,152.000000,1872.000000,450.000000,428.000000
IBADAN (IBEDC),235.229052,236.538056,203.970464,230.554058,199.276902,181.076522,240.307936,283.575942,281.256615,260.260700,...,209.039693,172.636683,209.749337,213.432256,208.278685,216.275267,226.257005,2592.221941,595.818276,650.810957
IKEJA (IEDC),250.701908,253.557094,235.416870,264.490572,204.174692,184.537592,248.026049,312.804933,333.388305,313.725722,...,286.353019,234.745843,278.008078,313.875054,322.564031,302.033831,327.235026,3601.395243,826.628976,951.832887
JOS (JEDC),91.000000,120.000000,68.300000,85.000000,60.000000,58.000000,71.000000,84.000000,109.000000,99.000000,...,82.154216,84.508640,83.899215,89.755187,109.561701,113.950913,122.937498,1168.459545,258.163042,346.450112
KADUNA (KDEDC),130.230000,127.430000,124.870000,134.610000,128.050000,99.800000,120.000000,147.000000,154.000000,156.900000,...,135.000000,93.000000,84.000000,81.000000,80.000000,81.970000,88.500000,1415.470000,258.000000,250.470000
KANO (KEDC),87.000000,72.870000,79.910000,63.400000,49.600000,49.640000,84.600000,102.110000,109.150000,123.700000,...,96.000000,86.000000,101.000000,116.000000,104.000000,112.000000,125.756793,1367.956793,303.000000,341.756793
PORT HARCOURT (PEDC),152.000000,134.630000,121.000000,122.000000,116.341150,105.180000,127.000000,153.000000,160.000000,153.000000,...,119.354532,121.325690,143.000000,141.390583,140.795510,143.000000,147.705137,1609.791269,405.716274,431.500647
YOLA (YEDC),21.000000,19.400000,19.000000,21.000000,19.400000,16.800000,24.000000,30.800000,34.000000,36.000000,...,37.607081,34.372491,36.882802,36.144205,37.378568,41.687244,42.679344,486.939140,107.399498,121.745156

In [34]:
data_22_2 = pd.read_excel('../data/raw_data/ELECTRICIY DATA 2015-Q2 2022.xlsx' ,skiprows = 65, header = 0, index_col = 0)[['Q1', 'Q2']]

In [35]:
data_22_2

                               Q1           Q2
DISCOS                5955.515410  5226.973067
ABUJA (AEDC)           649.000000   616.000000
BENIN (BEDC)           603.004095   546.155633
EKO (EKEDC)            754.387434   627.000000
ENUGU (EEDC)           530.000000   464.000000
IBADAN (IBEDC)         724.187538   621.405170
IKEJA (IEDC)           987.211879   835.721501
JOS (JEDC)             296.361134   267.485257
KADUNA (KDEDC)         473.000000   434.000000
KANO (KEDC)            413.200000   310.000000
PORT HARCOURT (PEDC)   395.569923   377.004425
YOLA (YEDC)            129.593405   128.201081